AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  llmtextprocessing:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 123
      Role: >-
        arn:aws:iam::855329302620:role/service-role/llm-text-processing-role-8dg1hzbh
      Environment:
        Variables:
          OPENAI_API_KEY: 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
      Layers:
        - 'arn:aws:lambda:us-east-1:855329302620:layer:LangChain:2'
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
