AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: An AWS Serverless lambda function that converts text to speech
Resources:
  texttospeechlambda:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Description: ""
      MemorySize: 128
      Timeout: 123
      Role: >-
        arn:aws:iam::your-aws-account-id:role/your-role-name
      Environment:
        Variables:
          AWS_BUCKET_NAME: your-bucket-name
          ELEVENLABS_API_KEY: elevenlabs-api-key
          GOOGLE_CLOUD_TEXT_TO_SPEECH_API_KEY: google-cloud-text-to-speech-api-key
      Layers:
        - "paster aws lambda layer arn"
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
